import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowLeft,ChevronRight,Clock3,LogIn,LogOut,Menu,Pencil,Search,Star,Trash2,X} from 'lucide-react';
import './index.css';

type Article={id:string;title:string;excerpt:string;category:string;author:string;publishedAt:string;body:string;status:'published'|'draft';featured?:boolean;tags?:string[];slug:string;imageUrl?:string;seoTitle?:string;seoDescription?:string};
const categories=['Усі','Львів','Область','Політика','Кримінал','Інфраструктура','Суспільство'];
const date=(v:string)=>new Date(v).toLocaleString('uk-UA',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'});

async function api(path:string,options:RequestInit={}){const r=await fetch(path,{...options,headers:{'Content-Type':'application/json',...(options.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Помилка');return d}

function App(){
 const [articles,setArticles]=useState<Article[]>([]),[category,setCategory]=useState('Усі'),[query,setQuery]=useState(''),[selected,setSelected]=useState<Article|null>(null),[menu,setMenu]=useState(false),[admin,setAdmin]=useState(!!localStorage.getItem('adminToken')),[login,setLogin]=useState(false),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[editing,setEditing]=useState<string|null>(null),[form,setForm]=useState<any>({title:'',excerpt:'',category:'Львів',body:'',status:'published',featured:false,tags:'',slug:'',imageUrl:'',seoTitle:'',seoDescription:''}),[error,setError]=useState('');
 const load=()=>{const token=localStorage.getItem('adminToken');return api('/api/articles',token?{headers:{Authorization:`Bearer ${token}`}}:{}).then(d=>setArticles(d.articles||[]));};
 useEffect(()=>{load().catch(e=>setError(e.message||'Не вдалося завантажити новини'))},[]);
 const published=useMemo(()=>articles.filter(a=>a.status!=='draft'),[articles]);
 const filtered=useMemo(()=>published.filter(a=>(category==='Усі'||a.category===category)&&(a.title+' '+a.excerpt+' '+(a.tags||[]).join(' ')).toLowerCase().includes(query.toLowerCase())),[published,category,query]);
 const featured=filtered.find(a=>a.featured)||filtered[0],latest=filtered.filter(a=>a.id!==featured?.id).slice(0,6),popular=published.slice(0,5);
 const logout=()=>{localStorage.removeItem('adminToken');setAdmin(false)};
 const doLogin=async()=>{try{const d=await api('/api/auth',{method:'POST',body:JSON.stringify({email,password})});localStorage.setItem('adminToken',d.token);setAdmin(true);setLogin(false);setPassword('');setError('')}catch(e:any){setError(e.message)}};
 const save=async()=>{const token=localStorage.getItem('adminToken');const payload={...form,tags:String(form.tags||'').split(',').map((x:string)=>x.trim()).filter(Boolean),publishedAt:new Date().toISOString(),author:'Редакція'};try{await api(editing?`/api/articles?id=${editing}`:'/api/articles',{method:editing?'PUT':'POST',headers:{Authorization:`Bearer ${token}`},body:JSON.stringify(payload)});setEditing(null);setForm({title:'',excerpt:'',category:'Львів',body:'',status:'published',featured:false,tags:'',slug:'',imageUrl:'',seoTitle:'',seoDescription:''});load()}catch(e:any){alert(e.message)}};
 const edit=(a:Article)=>{setEditing(a.id);setForm({...a,tags:(a.tags||[]).join(',')});window.scrollTo({top:0,behavior:'smooth'})};
 const del=async(id:string)=>{await api(`/api/articles?id=${id}`,{method:'DELETE',headers:{Authorization:`Bearer ${localStorage.getItem('adminToken')}`}});load()};
 if(selected)return <div className="min-h-screen"><header className="border-b bg-white"><div className="mx-auto flex max-w-6xl items-center justify-between px-4 py-4"><button onClick={()=>setSelected(null)} className="flex items-center gap-2 font-bold"><ArrowLeft size={18}/> До новин</button><div className="brand text-lg">ЛЬВІВ <span>СЬОГОДНІ</span></div><div/></div></header><article className="mx-auto max-w-5xl px-4 py-10"><div className="mb-4 font-bold text-blue-700">{selected.category} · {date(selected.publishedAt)}</div><h1 className="text-4xl font-black leading-tight md:text-6xl">{selected.title}</h1>{selected.imageUrl&&<img src={selected.imageUrl} className="mt-8 max-h-[520px] w-full rounded-3xl object-cover"/>}<p className="mt-6 text-xl leading-relaxed text-slate-600">{selected.excerpt}</p><div className="mt-8 text-lg article-body">{selected.body}</div><div className="mt-8 flex flex-wrap gap-2">{(selected.tags||[]).map(t=><span className="rounded-full bg-slate-200 px-3 py-1 text-sm">#{t}</span>)}</div></article></div>;
 return <div className="min-h-screen"><header className="sticky top-0 z-40 border-b bg-white"><div className="mx-auto flex max-w-7xl items-center gap-3 px-4 py-3"><button onClick={()=>setMenu(!menu)} className="rounded-lg p-2"><Menu size={21}/></button><button className="brand text-lg" onClick={()=>{setCategory('Усі');setQuery('')}}>ЛЬВІВ <span>СЬОГОДНІ</span></button><div className="hidden flex-1 justify-center md:flex"><div className="flex w-full max-w-md items-center rounded-full border bg-slate-50 px-4"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Пошук новин..." className="w-full bg-transparent px-2 py-2 outline-none"/></div></div><div className="ml-auto">{admin?<button onClick={logout} className="flex items-center gap-2 rounded-full border px-3 py-2 text-sm font-semibold"><LogOut size={15}/> Вийти</button>:<button onClick={()=>setLogin(true)} className="flex items-center gap-2 rounded-full bg-slate-950 px-3 py-2 text-sm font-bold text-white"><LogIn size={15}/> Увійти</button>}</div></div>{menu&&<div className="border-t px-4 py-3 md:hidden"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Пошук новин..." className="w-full rounded-xl border px-3 py-2"/></div>}<nav className="overflow-x-auto border-t"><div className="mx-auto flex max-w-7xl gap-1 px-4 py-2">{categories.map(c=><button key={c} onClick={()=>setCategory(c)} className={`whitespace-nowrap rounded-full px-3 py-1.5 text-sm font-bold ${category===c?'bg-slate-950 text-white':'text-slate-600'}`}>{c}</button>)}{admin&&<button onClick={()=>document.getElementById('cms')?.scrollIntoView({behavior:'smooth'})} className="ml-auto rounded-full bg-blue-600 px-3 py-1.5 text-sm font-bold text-white">Редакція</button>}</div></nav></header>
 {login&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/40 p-4"><div className="w-full max-w-md rounded-3xl bg-white p-6"><div className="flex justify-between"><h2 className="text-2xl font-black">Вхід до редакції</h2><button onClick={()=>setLogin(false)}><X/></button></div><p className="mt-2 text-sm text-slate-500">Доступ лише для власника сайту.</p><input value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email" className="mt-5 w-full rounded-xl border px-4 py-3"/><input value={password} onChange={e=>setPassword(e.target.value)} type="password" placeholder="Пароль" className="mt-3 w-full rounded-xl border px-4 py-3"/>{error&&<div className="mt-3 text-sm font-semibold text-red-600">{error}</div>}<button onClick={doLogin} className="mt-4 w-full rounded-xl bg-blue-600 px-4 py-3 font-bold text-white">Увійти</button></div></div>}
 <main className="mx-auto max-w-7xl px-4 py-7">{error&&<div className="mb-5 rounded-2xl border border-red-200 bg-red-50 p-4 text-sm font-semibold text-red-700">{error}</div>}{featured&&<section className="grid gap-5 lg:grid-cols-[1.65fr_.85fr]"><button onClick={()=>setSelected(featured)} className="rounded-3xl bg-slate-950 p-7 text-left text-white md:p-10"><div className="mb-5 flex items-center gap-2 text-xs font-black uppercase text-blue-300"><Star size={14}/> Головне</div><h1 className="text-4xl font-black leading-tight md:text-6xl">{featured.title}</h1><p className="mt-5 text-lg text-slate-300">{featured.excerpt}</p><div className="mt-7 text-sm text-slate-400">{featured.category} · {date(featured.publishedAt)}</div><span className="mt-6 inline-flex rounded-full bg-white px-4 py-2 text-sm font-black text-slate-950">Читати <ChevronRight size={16}/></span></button><aside className="rounded-3xl border bg-white p-5"><div className="mb-4 flex items-center justify-between"><h2 className="text-xl font-black">Популярне</h2><Clock3 size={18}/></div>{popular.map((a,i)=><button key={a.id} onClick={()=>setSelected(a)} className="flex w-full gap-4 border-t py-4 text-left"><span className="text-2xl font-black text-slate-200">{String(i+1).padStart(2,'0')}</span><span><b className="text-xs text-blue-600">{a.category}</b><span className="block font-bold">{a.title}</span></span></button>)}</aside></section>}
 <section className="mt-9"><div className="mb-4 flex justify-between border-b pb-3"><h2 className="text-2xl font-black">Останні новини</h2><span className="text-sm text-slate-400">{filtered.length} матеріалів</span></div><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{latest.map(a=><button key={a.id} onClick={()=>setSelected(a)} className="rounded-2xl border bg-white p-5 text-left shadow-sm"><div className="text-xs font-black text-blue-600">{a.category} · {date(a.publishedAt)}</div><h3 className="mt-2 text-xl font-black">{a.title}</h3><p className="mt-3 line-clamp-3 text-sm leading-6 text-slate-500">{a.excerpt}</p></button>)}</div></section>
 {categories.slice(1).map(cat=>{const items=published.filter(a=>a.category===cat).slice(0,3);return items.length?<section key={cat} className="mt-10"><div className="mb-4 flex justify-between border-b pb-3"><h2 className="text-2xl font-black">{cat}</h2></div><div className="grid gap-4 md:grid-cols-3">{items.map(a=><button key={a.id} onClick={()=>setSelected(a)} className="rounded-2xl border bg-white p-5 text-left"><div className="text-xs font-black text-blue-600">{date(a.publishedAt)}</div><h3 className="mt-2 font-black">{a.title}</h3><p className="mt-2 line-clamp-2 text-sm text-slate-500">{a.excerpt}</p></button>)}</div></section>:null})}
 {admin&&<section id="cms" className="mt-12 rounded-3xl border bg-white p-5"><div className="mb-6 flex items-center justify-between"><h2 className="text-3xl font-black">Редакція</h2><span className="text-sm text-slate-500">Адміністратор: denys20smm@gmail.com</span></div><div className="grid gap-6 lg:grid-cols-2"><div className="space-y-3"><input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="Заголовок" className="w-full rounded-xl border px-4 py-3"/><textarea value={form.excerpt} onChange={e=>setForm({...form,excerpt:e.target.value})} placeholder="Лід" rows={3} className="w-full rounded-xl border px-4 py-3"/><select value={form.category} onChange={e=>setForm({...form,category:e.target.value})} className="w-full rounded-xl border px-4 py-3">{categories.slice(1).map(c=><option key={c}>{c}</option>)}</select><textarea value={form.body} onChange={e=>setForm({...form,body:e.target.value})} placeholder="Текст" rows={9} className="w-full rounded-xl border px-4 py-3"/><input value={form.slug} onChange={e=>setForm({...form,slug:e.target.value})} placeholder="slug" className="w-full rounded-xl border px-4 py-3"/><input value={form.tags} onChange={e=>setForm({...form,tags:e.target.value})} placeholder="Теги через кому" className="w-full rounded-xl border px-4 py-3"/><label className="flex gap-2"><input type="checkbox" checked={form.featured} onChange={e=>setForm({...form,featured:e.target.checked})}/> Головний матеріал</label><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})} className="w-full rounded-xl border px-4 py-3"><option value="published">Опубліковано</option><option value="draft">Чернетка</option></select><button onClick={save} className="w-full rounded-xl bg-blue-600 px-4 py-3 font-bold text-white">{editing?'Зберегти зміни':'Опублікувати'}</button></div><div className="space-y-2">{articles.map(a=><div key={a.id} className="flex items-center gap-2 rounded-xl border p-3"><div className="min-w-0 flex-1"><div className="text-xs font-bold text-blue-600">{a.category}</div><div className="truncate font-bold">{a.title}</div></div><button onClick={()=>edit(a)} className="p-2 text-blue-600"><Pencil size={17}/></button><button onClick={()=>del(a.id)} className="p-2 text-red-600"><Trash2 size={17}/></button></div>)}</div></div></section>}
 </main><footer className="mt-12 border-t bg-slate-950 px-4 py-10 text-slate-400"><div className="mx-auto max-w-7xl"><div className="brand text-xl text-white">ЛЬВІВ <span>СЬОГОДНІ</span></div><p className="mt-3 text-sm">Новинне медіа про Львів та область.</p></div></footer></div>
}
createRoot(document.getElementById('root')!).render(<App/>);
